remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "neon"
repository: "Y-o-p/Y-o-p.github.io"
title: "Jesse Rheal's Portfolio"
name: "Jesse Rheal"

# Site Author
author:
  name             : "Jesse Rheal"
  avatar           : "imgs/me.jpeg"
  bio              : "Currently working on this website."
  location         : "Huntsville, AL"
  email            : "jessecolerheal@live.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:jessecolerheal@live.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/Y-o-p"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-include-cache